name: Run Hourly Script

on:
  schedule:
    - cron: "0 * * * *"  # каждый час
  workflow_dispatch:

jobs:
  run-hourly:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: 📦 Устанавливаем зависимости
        run: |
          pip install -r requirements.txt

      - name: 🚀 Запускаем donload.py
        run: |
          python download_video.py

      - name: 🚀 Запускаем edit.py
        run: |
          python edit_video.py
          
      - name: 🚀 Запускаем upload.py
        run: |
          python upload_video.py
